[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[window]

decorations = "None"
opacity = 0.8

[font]
normal = { family = "FiraCode Nerd Font" }

[cursor]
style = { shape = "Block" }
vi_mode_style = { shape = "Block" }
